module.exports = { parse: parse, write: write }

var fs = require('fs')

function parse(hosts){
  var lines = (hosts+'').split('\n')
  var phost = {}
  lines.forEach(function (line){
    var hasSpace = false
    if (line.indexOf('#') === 0) return
    line = line.split(/\s|\\t/)

    line = line.filter(function (t){
      if (t == '') return false
      return t
    })
    if (!line[1]) return 
    phost[line[1]] = line[0]
  })
  return phost
}

function write(obj){
  var str = '# Autogenerated by Kaixo\n'
  Object.keys(obj).forEach(function (host){
    if (obj[host].hostname) str += obj[host].hostname
    else str += obj[host]
    str += '\t' + host + '\n'
  })
  fs.writeFileSync('/etc/hosts', str, 'utf8')
  return true
}
